translations/*.qm /usr/share/downloadmanager/translations
desktop/downloadmanager.desktop /usr/share/applications
data/uos-downloadmanager-task.db /usr/share/downloadmanager/database
data/downloader4.svg /usr/share/icons/hicolor/scalable/apps
data/downloader4.svg /usr/share/downloadmanager/icons/logo
docs/aria2.conf /usr/share/downloadmanager/config
docs/config.conf /usr/share/downloadmanager/config
