#!/bin/bash

str=`cat /usr/share/applications/mimeapps.list | grep x-scheme-handler`

if [ -z "$str" ]; then
 echo >> /usr/share/applications/mimeapps.list
 sed -i '$d' /usr/share/applications/mimeapps.list
 echo x-scheme-handler/downloader=dlmextensionservice.desktop >> /usr/share/applications/mimeapps.list
fi

display=$DISPLAY
user=$(who | grep '('$display')' | awk '{print $1}')
echo $user
cp /usr/share/downloader/config/browser.downloader.autostart.json  /home/$user/.config/browser/NativeMessagingHosts/